name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  - cron: '00 16 * * 1'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
        check-latest: true
    - run: go run github.com/onsi/ginkgo/ginkgo -p -r -race -randomizeAllSpecs -randomizeSuites -keepGoing

  vet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
        check-latest: true
    - run: go vet ./...

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v2
      with:
        go-version-file: 'go.mod'
        check-latest: true
    - uses: golangci/golangci-lint-action@v3.2.0
      with:
        args: --config .golangci.yml
